### PR TITLE
Add Ads Manager exercise

### LINKED ISSUE #3: Exercício: Ads Manager UI
Oii Yara, como vão as coisas? Tudo certo? Bora de exercício de CSS :smile:

Dessa vez vamos copiar um UI que seria quase uma página completa de um *ads manager* também criado pela [Ildiko Gaspar](https://dribbble.com/ildiesign). Escolhi esse design para você exercitar tabelas e flexbox.

Note que a segunda linha está diferente pois ela está ativa por conta do cursor do mouse estar em cima. Não se esqueça de adicionar esse **estado** usando uma das **pseudo-classes** que já vimos antes.

Na logo da página há um ícone que é um pouco oval, então vetorizei ele:

<details>
  <summary>Ver logo</summary>

ui-design-daily-logo

</details>

Também vetorizei os ícones de lixeira e pesquisa para que você possa usar no seu exercício:

<details>
  <summary>Ver icones</summary>

search-icon

trash-can

</details>

Não se esqueça de enviar o exercício quando finalizar via Pull Request. Isso é bem importante pois vou começar a revisar usando o próprio Github.

Nesse exercício você vai trabalhar com umas coisinhas novas como *pseudo-class* mas acredito que você vá conseguir sem problemas. Mas qualquer dúvida, não hesite em me chamar. Bom coding! :sunglasses:

Link: https://dribbble.com/shots/10735983-Ads-Manager-UI-Design

Ads Manager UI by Ildiko Gaspa

### PR DESCRIPTION
**Pull request by YaraWS**
* Couldn't insert the searching symbol inside the search box
* Had some dificulty aligning the tittle on top of the table

### CODE REVIEW

**Comment by parkejunior** [comment]
The exercise is correctly organized inside its folder, but to follow the pattern, please put it inside the directory like `/[language]/[exercise title]/[username]`.

**Comment by parkejunior** [comment]
i changed the title for readability. "First commit" don't explain about this pull request.

**Comment by YaraWS** [comment]
I hope the pattern is correct. Follow the cargo design agency files.

**Comment by parkejunior** [comment]
The exercise follows the pattern correctly, but this issue is only for the Ads Manager exercise and its files remain inside the exercise's root folder. Please, you should open a new pull request for Cargo Design Agency exercise.

**Comment by YaraWS** [comment]
* I moved the files from Ads Manager into a folder named yara
* I deleted the folder Cargo Design

**Comment by parkejunior** [comment]
Ok, that's great! You should add more changes when you need.

**Pull request merged**
